export const data = [
    {
    ID : "1",
    Name: "Raja",
    Batch: "B-43 Tamil",
    Email: "rajakumar@gmail.com",
    Experience: 1,
},
{
    ID : "2",
    Name: "Arun",
    Batch: "B-43 Tamil",
    Email: "arunkumar@gmail.com",
    Experience: 2,
},
{
    ID : "3",
    Name: "Sam",
    Batch: " B-43 Tamil",
    Email: "sam12@gmail.com",
    Experience: 3,
},
{
    ID : "4",
    Name: "Parba",
    Batch: "B-43 Tamil",
    Email: "Praba32@gmail.com",
    Experience: 2,
},
{
    ID : "5",
    Name: "Selva jee",
    Batch: "B-43 Tamil",
    Email: "selva21@gmail.com",
    Experience: 2,
},
{
    ID : "6",
    Name: "Jhon",
    Batch: "B-43 Tamil",
    Email: "john65@gmail.com",
    Experience: 2,
},
{
    ID : "7",
    Name: "Vishnu",
    Batch: "B-43 Tamil",
    Email: "visu123@gmail.com",
    Experience: 1.5,
},
{
    ID : "8",
    Name: "Kumar",
    Batch: "B-43 Tamil",
    Email: "kumar5@gmail.com",
    Experience: 1,
},
{
    ID : "9",
    Name: "Sugan",
    Batch: "B-43 Tamil",
    Email: "sugan35@gmail.com",
    Experience: 2,
},
{
    ID : "10",
    Name: "Rajesh",
    Batch: "B-43 Tamil",
    Email: "rajesh85@gmail.com",
    Experience: 1,
}
]
